### ISSUE TITLE
Implement text truncating in the File input component

### ISSUE THREAD

**Issue by subhadip001** [subhadip001/spira-app#9]
for larger file names (specially in smaller screens) implement text truncating using css (preferable) and add on hover full text (like tooltip) if possible.

**Comment by thejasviES** [comment]
Please provide a screenshot of that component if possible

**Comment by subhadip001** [comment]
![image](https://github.com/user-attachments/assets/998feffb-29c5-40fa-99a9-026299c5c3df)
